sudo: required

arch:
  packages:
    - cmake
    - xorg-server-xwayland
    - asciidoc
    - pcre
    - json-c
    - pixman
    - wayland
    - libxkbcommon
    - libinput
    - libx11
    - libxcb
    - xcb-util-image
    - libgl
    - mesa
    - pango
    - cairo
  script:
    - "bash .ci/build.sh"

script:
  - export ARCH_TRAVIS_ARCH_ISO=$(date +%Y.%m).01
  - "curl -s https://raw.githubusercontent.com/mikkeloscar/arch-travis/master/arch-travis.sh | bash"
